import React, { createContext, useContext, useState, useEffect, useMemo, useRef, ReactNode } from 'react';
import {
  AnyUser,
  VSUser,
  VolunteerUser,
  Unit,
  PlantingSubmission,
  NotificationLog,
  TagApprovalStatus,
} from './types';
import {
  INITIAL_VS_USERS,
  INITIAL_VOLUNTEERS,
  INITIAL_UNITS,
  INITIAL_SUBMISSIONS,
} from './initialData';
import { formatDate, parseDate } from './thanalWindow';
import { supabase } from './supabase';

interface ThanalContextType {
  currentUser: AnyUser | null;
  setCurrentUser: (user: AnyUser | null) => void;
  units: Unit[];
  vsUsers: VSUser[];
  volunteers: VolunteerUser[];
  submissions: PlantingSubmission[];
  notifications: NotificationLog[];
  systemDate: string; // YYYY-MM-DD
  setSystemDate: (dateStr: string) => void;
  advanceSystemDateByDays: (days: number) => void;
  resetSystemDate: () => void;
  
  // Auth & Registration
  login: (id: string, password?: string) => Promise<{ success: boolean; message: string; user?: AnyUser }>;
  logout: () => void;
  registerVs: (data: Omit<VSUser, 'role' | 'status' | 'createdAt'>) => Promise<{ success: boolean; message: string }>;
  registerVolunteer: (data: Omit<VolunteerUser, 'role' | 'status' | 'createdAt'> & { batch?: string }) => Promise<{ success: boolean; message: string }>;

  // VS Actions
  approveVolunteer: (volunteerId: string, vsId: string) => void;
  rejectVolunteer: (volunteerId: string) => Promise<void>;

  // Planting & Tag Actions
  submitPlanting: (data: {
    volunteerId: string;
    treeSpecies: string;
    plantingDate: string;
    locationName: string;
    coordinates?: { lat: number; lng: number };
    description: string;
    photoUrl: string;
    photoFileName: string;
    tagApprovalStatus: TagApprovalStatus;
    tagNotes?: string;
  }) => Promise<{ success: boolean; message: string; submissionId?: string }>;

  updateTagStatus: (
    submissionId: string,
    newStatus: TagApprovalStatus,
    tagNotes?: string
  ) => void;

  // Google Drive (per unit)
  driveSettings: { scriptUrl: string; folderUrl: string } | null;
  saveDriveSettings: (scriptUrl: string, folderUrl: string) => Promise<{ success: boolean; message: string }>;
  testDriveConnection: (scriptUrl: string) => Promise<{ success: boolean; message: string }>;

  // Notification helpers
  refreshNotifications: () => Promise<void>;
  
  // Storage Reset & Production Initialization
  resetDatabase: () => void;
  isProductionMode: boolean;
  setIsProductionMode: (val: boolean) => void;
}

const ThanalContext = createContext<ThanalContextType | undefined>(undefined);

/**
 * Human-friendly ID shown in the UI, e.g. "141-V007" (volunteer 7 of unit 141) or
 * "141-VS" (the unit's VS). It is generated by the database (users.short_id).
 * Falls back to a short slice of the UUID if the code isn't available yet.
 * Display only: keep using the full id for queries and comparisons.
 */
export const displayId = (user: { id: string; shortCode?: string }): string =>
  user.shortCode || `THN-${user.id.replace(/-/g, '').slice(0, 6).toUpperCase()}`;

const STORAGE_KEYS = {
  CURRENT_USER: 'thanal_current_user_prod_v4',
  UNITS: 'thanal_units_prod_v4',
  VS_USERS: 'thanal_vs_users_prod_v4',
  VOLUNTEERS: 'thanal_volunteers_prod_v4',
  SUBMISSIONS: 'thanal_submissions_prod_v4',
  SYSTEM_DATE: 'thanal_system_date_prod_v4',
  IS_PRODUCTION_MODE: 'thanal_is_production_mode_prod_v4',
};

export const ThanalProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Initial date anchor: default to 2026-10-05
  const defaultDateStr = '2026-10-05';

  const [isProductionMode, setIsProductionModeState] = useState<boolean>(true);

  const [systemDate, setSystemDateState] = useState<string>(() => {
    return localStorage.getItem(STORAGE_KEYS.SYSTEM_DATE) || defaultDateStr;
  });

  const [units, setUnits] = useState<Unit[]>(() => {
    const saved = localStorage.getItem(STORAGE_KEYS.UNITS);
    return saved ? JSON.parse(saved) : INITIAL_UNITS;
  });

  const [vsUsers, setVsUsers] = useState<VSUser[]>(() => {
    const saved = localStorage.getItem(STORAGE_KEYS.VS_USERS);
    return saved ? JSON.parse(saved) : INITIAL_VS_USERS;
  });

  const [volunteers, setVolunteers] = useState<VolunteerUser[]>(() => {
    const saved = localStorage.getItem(STORAGE_KEYS.VOLUNTEERS);
    return saved ? JSON.parse(saved) : INITIAL_VOLUNTEERS;
  });

  const [submissions, setSubmissions] = useState<PlantingSubmission[]>(() => {
    const saved = localStorage.getItem(STORAGE_KEYS.SUBMISSIONS);
    return saved ? JSON.parse(saved) : INITIAL_SUBMISSIONS;
  });

  // Email log. Filled ONLY from the notification_log table in Supabase, which the
  // daily mail job writes after an email was really sent. Never created in the browser.
  const [notifications, setNotifications] = useState<NotificationLog[]>([]);

  const [driveSettings, setDriveSettings] = useState<{ scriptUrl: string; folderUrl: string } | null>(null);
  const tagTimers = useRef<Record<string, ReturnType<typeof setTimeout>>>({});

  // Default logged in user: null (opens as clean portal ready for real user registrations)
  const [currentUser, setCurrentUser] = useState<AnyUser | null>(() => {
    const saved = localStorage.getItem(STORAGE_KEYS.CURRENT_USER);
    return saved ? JSON.parse(saved) : null;
  });

  // Save changes to LocalStorage
  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.UNITS, JSON.stringify(units));
  }, [units]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.VS_USERS, JSON.stringify(vsUsers));
  }, [vsUsers]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.VOLUNTEERS, JSON.stringify(volunteers));
  }, [volunteers]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.SUBMISSIONS, JSON.stringify(submissions));
  }, [submissions]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.SYSTEM_DATE, systemDate);
  }, [systemDate]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.IS_PRODUCTION_MODE, String(isProductionMode));
  }, [isProductionMode]);

  useEffect(() => {
    if (currentUser) {
      localStorage.setItem(STORAGE_KEYS.CURRENT_USER, JSON.stringify(currentUser));
    } else {
      localStorage.removeItem(STORAGE_KEYS.CURRENT_USER);
    }
  }, [currentUser]);

  // Emails are sent by the scheduled mail job (see apps-script/ThanalMailer.gs), not by the browser.
  // This just reloads the log of emails that were really sent.
  const refreshNotifications = async () => {
    await loadUnitData();
  };

  const setSystemDate = (newDateStr: string) => {
    setSystemDateState(newDateStr);
  };

  const advanceSystemDateByDays = (days: number) => {
    const current = parseDate(systemDate);
    current.setDate(current.getDate() + days);
    setSystemDateState(formatDate(current));
  };

  const resetSystemDate = () => {
    setSystemDateState(defaultDateStr);
  };

  // ---- Supabase sync helpers ----
  const fetchUnitCodeMap = async (): Promise<Record<string, string>> => {
    const { data } = await supabase.from('units').select('id, unit_number');
    const map: Record<string, string> = {};
    (data || []).forEach((u: any) => {
      map[u.id] = String(u.unit_number);
    });
    return map;
  };

  const rowToUser = (row: any, codeMap: Record<string, string>): VSUser | VolunteerUser | null => {
    const localUnit = units.find((u) => u.code === codeMap[row.unit_id]);
    if (!localUnit) return null;
    const base = {
      id: row.user_id as string,
      name: row.name as string,
      email: row.email as string,
      phone: '',
      password: '',
      status: String(row.account_status).toUpperCase() as VSUser['status'],
      createdAt: row.created_at ? String(row.created_at).slice(0, 10) : systemDate,
      college: localUnit.college,
      unitId: localUnit.id,
      unitCode: localUnit.code,
      shortCode: (row.short_id as string | undefined) || undefined,
      batch: (row.batch as string | undefined) || undefined,
    };
    if (String(row.role).toUpperCase() === 'VS') {
      return { ...base, role: 'VS', dob: row.date_of_birth || '' } as VSUser;
    }
    return { ...base, role: 'VOLUNTEER', dob: row.date_of_birth || '' } as VolunteerUser;
  };

  // Pull the users this person is allowed to see (RLS decides) from Supabase.
  const loadUnitData = async () => {
    const { data, error } = await supabase.from('users').select('*');
    if (error) {
      console.error('Supabase users load failed:', error);
      return;
    }
    const codeMap = await fetchUnitCodeMap();
    const rows = (data || [])
      .map((r: any) => rowToUser(r, codeMap))
      .filter((r): r is VSUser | VolunteerUser => r !== null);
    // Supabase is the source of truth: replace local lists (don't merge) so anything
    // deleted in the database disappears from the dashboard too. Rejected = gone.
    const vols = rows.filter(
      (r): r is VolunteerUser => r.role === 'VOLUNTEER' && r.status !== 'REJECTED'
    );
    const vss = rows.filter((r): r is VSUser => r.role === 'VS');
    setVolunteers(vols);
    setVsUsers(vss);

    // Planting submissions (RLS: volunteers see their own, VS see their unit)
    const { data: pRows, error: pError } = await supabase.from('plantings').select('*');
    if (pError) {
      console.error('Supabase plantings load failed:', pError);
    } else {
      const subs: PlantingSubmission[] = [];
      (pRows || []).forEach((p: any) => {
        const owner = rows.find((r) => r.id === p.volunteer_id);
        if (!owner) return;
        subs.push({
          id: p.id,
          volunteerId: p.volunteer_id,
          volunteerName: owner.name,
          unitId: owner.unitId,
          unitCode: owner.unitCode,
          year: p.year,
          treeSpecies: p.tree_species || '',
          plantingDate: p.planting_date || '',
          locationName: p.location_name || '',
          description: p.description || '',
          photoUrl: p.photo_url || '',
          photoFileName: p.photo_file_name || '',
          tagApprovalStatus: (p.tag_status || 'Pending') as TagApprovalStatus,
          tagNotes: p.tag_notes || undefined,
          submittedAt: p.submitted_at,
          updatedAt: p.updated_at,
          driveFolderExpected: `THANAL/${owner.unitCode}/${owner.name}/${p.year}`,
          driveLink: p.drive_link || undefined,
        });
      });
      setSubmissions(subs);
    }

    // Emails that were really sent (RLS: volunteers see their own, VS see their unit's)
    const { data: nRows, error: nError } = await supabase
      .from('notification_log')
      .select('*')
      .order('sent_at', { ascending: false });
    if (nError) {
      console.error('Supabase notification_log load failed:', nError);
    } else {
      const logs: NotificationLog[] = (nRows || [])
        .map((n: any) => {
          const owner = rows.find((r) => r.id === n.volunteer_id);
          if (!owner) return null;
          return {
            id: n.id,
            volunteerId: n.volunteer_id,
            volunteerName: owner.name,
            recipientEmail: n.recipient_email,
            type: n.type,
            subject: n.subject,
            body: n.body,
            sentAt: n.sent_at,
            year: n.year,
          } as NotificationLog;
        })
        .filter((n: NotificationLog | null): n is NotificationLog => n !== null);
      setNotifications(logs);
    }

    // This unit's Drive connection (RLS: only the unit's own row is visible)
    const { data: ds } = await supabase.from('unit_drive_settings').select('*').maybeSingle();
    setDriveSettings(ds ? { scriptUrl: ds.script_url, folderUrl: ds.folder_url || '' } : null);
  };

  useEffect(() => {
    if (!currentUser) return;
    loadUnitData();
    if (currentUser.role !== 'VS') return;
    const timer = setInterval(loadUnitData, 20000);
    return () => clearInterval(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentUser?.id]);

  // AUTH
  const login = async (id: string, password?: string) => {
    const trimmedId = id.trim();
    if (!trimmedId) return { success: false, message: 'Please enter your ID.' };

    // 1b. Email + password: real Supabase sign-in (VS and Volunteers)
    if (trimmedId.includes('@')) {
      const { data: signIn, error: signInError } = await supabase.auth.signInWithPassword({
        email: trimmedId,
        password: password || '',
      });
      if (signInError || !signIn.user) {
        return {
          success: false,
          message:
            signInError?.message === 'Invalid login credentials'
              ? 'Incorrect email or password.'
              : signInError?.message || 'Sign in failed.',
        };
      }
      const { data: row, error: rowError } = await supabase
        .from('users')
        .select('*')
        .eq('user_id', signIn.user.id)
        .maybeSingle();
      const codeMap = await fetchUnitCodeMap();
      const user = row ? rowToUser(row, codeMap) : null;
      if (rowError || !user) {
        await supabase.auth.signOut();
        return { success: false, message: 'Your profile was not found. Please register again.' };
      }
      if (user.status !== 'APPROVED') {
        await supabase.auth.signOut();
        const msg =
          user.status === 'PENDING'
            ? `Your account is PENDING approval from your Unit (${user.unitCode}) VS.`
            : user.status === 'SUSPENDED'
            ? 'Your account has been suspended. Please contact your unit VS.'
            : 'Your registration was not approved by your Unit VS.';
        return { success: false, message: msg };
      }
      if (user.role === 'VS') {
        const { data: vsOk } = await supabase.rpc('is_vs_email_allowed', { p_email: user.email });
        if (!vsOk) {
          await supabase.auth.signOut();
          return { success: false, message: 'This email is not authorised as a VS.' };
        }
        setVsUsers((prev) => [...prev.filter((v) => v.email.toLowerCase() !== user.email.toLowerCase()), user]);
      } else {
        setVolunteers((prev) => [...prev.filter((v) => v.email.toLowerCase() !== user.email.toLowerCase()), user as VolunteerUser]);
      }
      setCurrentUser(user);
      return { success: true, message: `Welcome, ${user.name}!`, user };
    }

    // 2. Check VS
    const foundVs = vsUsers.find(
      (v) => v.id.toLowerCase() === trimmedId.toLowerCase() || v.email.toLowerCase() === trimmedId.toLowerCase()
    );
    if (foundVs) {
      if (foundVs.status === 'PENDING') {
        return {
          success: false,
          message: 'Your VS account is currently PENDING approval.',
        };
      }
      if (foundVs.status === 'SUSPENDED') {
        return {
          success: false,
          message: 'Your VS account has been suspended.',
        };
      }
      if (foundVs.status === 'REJECTED') {
        return {
          success: false,
          message: 'Your VS application was not approved.',
        };
      }
      setCurrentUser(foundVs);
      return { success: true, message: `Welcome back, VS ${foundVs.name}!`, user: foundVs };
    }

    // 3. Check Volunteer
    const foundVol = volunteers.find(
      (v) => v.id.toLowerCase() === trimmedId.toLowerCase() || v.email.toLowerCase() === trimmedId.toLowerCase()
    );
    if (foundVol) {
      if (foundVol.status === 'PENDING') {
        return {
          success: false,
          message: `Your Volunteer account is PENDING approval from your Unit (${foundVol.unitCode}) VS.`,
        };
      }
      if (foundVol.status === 'REJECTED') {
        return {
          success: false,
          message: 'Your Volunteer registration was rejected by your Unit VS.',
        };
      }
      setCurrentUser(foundVol);
      return { success: true, message: `Welcome, ${foundVol.name}!`, user: foundVol };
    }

    return { success: false, message: 'Account not found with this ID or Email.' };
  };

  const logout = () => {
    supabase.auth.signOut();
    setDriveSettings(null);
    setCurrentUser(null);
  };

  // VS Registration
  const registerVs = async (data: Omit<VSUser, 'role' | 'status' | 'createdAt'>) => {
    const existing = vsUsers.find(
      (v) => v.id.toLowerCase() === data.id.toLowerCase() || v.email.toLowerCase() === data.email.toLowerCase()
    );
    if (existing) {
      return { success: false, message: 'A VS with this ID or Email is already registered.' };
    }

    // Only the single email whitelisted in the database may register as a VS
    // (is_vs_email_allowed is the source of truth; it is also enforced in the database).
    const { data: vsAllowed, error: vsAllowedError } = await supabase.rpc('is_vs_email_allowed', {
      p_email: data.email.trim(),
    });
    if (vsAllowedError) {
      return { success: false, message: `Could not verify VS email: ${vsAllowedError.message}` };
    }
    if (!vsAllowed) {
      return {
        success: false,
        message: 'This email is not authorised for VS registration.',
      };
    }

    try {
      const { data: unitRow, error: unitError } = await supabase
        .from('units')
        .select('id, unit_number')
        .eq('unit_number', data.unitCode)
        .maybeSingle();

      if (unitError) {
        console.error('Supabase unit lookup failed:', unitError);
        return { success: false, message: `Could not load the selected NSS unit: ${unitError.message}` };
      }
      if (!unitRow) {
        return {
          success: false,
          message: `NSS Unit ${data.unitCode} is not configured in Supabase yet. Add it to public.units first.`,
        };
      }

      const { data: authData, error: authError } = await supabase.auth.signUp({
        email: data.email.trim(),
        password: data.password || '',
        options: {
          data: {
            name: data.name.trim(),
            role: 'VS',
            unit_id: unitRow.id,
            unit_number: data.unitCode,
            date_of_birth: data.dob,
          },
        },
      });

      if (authError) {
        console.error('Supabase Auth signup failed:', authError);
        return { success: false, message: `Registration failed: ${authError.message}` };
      }
      if (!authData.user) {
        return { success: false, message: 'Registration failed: Supabase did not return a user account.' };
      }

      const { error: profileError } = await supabase.from('users').insert({
        user_id: authData.user.id,
        name: data.name.trim(),
        email: data.email.trim(),
        role: 'VS',
        unit_id: unitRow.id,
        date_of_birth: data.dob || null,
        account_status: 'APPROVED',
      });

      if (profileError) {
        console.error('Supabase users insert failed:', profileError);
        return {
          success: false,
          message: `Auth account was created, but the THANAL profile could not be saved: ${profileError.message}`,
        };
      }

      const newVs: VSUser = {
        ...data,
        role: 'VS',
        status: 'APPROVED',
        approvedAt: systemDate,
        createdAt: systemDate,
      };
      setVsUsers((prev) => [...prev.filter((v) => v.email.toLowerCase() !== data.email.toLowerCase()), newVs]);

      return {
        success: true,
        message: 'VS registration successful! You can now log in with your credentials.',
      };
    } catch (error) {
      console.error('Unexpected VS registration error:', error);
      return { success: false, message: 'Registration failed unexpectedly. Please try again.' };
    }
  };

  // Volunteer Registration
  const registerVolunteer = async (data: Omit<VolunteerUser, 'role' | 'status' | 'createdAt'> & { batch?: string }) => {
    // Batch = the 2-digit year the volunteer joined NSS, e.g. "24" or "25".
    const batch = String(data.batch || '').trim();
    if (batch && !/^\d{2}$/.test(batch)) {
      return { success: false, message: 'Please select a valid batch (e.g. 24 or 25).' };
    }
    try {
      // Resolve the selected unit in Supabase. The local UI uses the unit code (141/257/265),
      // while users.unit_id must contain the actual UUID from public.units.id.
      const { data: unitRow, error: unitError } = await supabase
        .from('units')
        .select('id, unit_number')
        .eq('unit_number', data.unitCode)
        .maybeSingle();

      if (unitError) {
        console.error('Supabase unit lookup failed:', unitError);
        return { success: false, message: `Could not load the selected NSS unit: ${unitError.message}` };
      }

      if (!unitRow) {
        return {
          success: false,
          message: `NSS Unit ${data.unitCode} is not configured in Supabase yet. Add it to public.units first.`,
        };
      }

      // Create the real authentication account. Never store the password in public.users.
      const { data: authData, error: authError } = await supabase.auth.signUp({
        email: data.email.trim(),
        password: data.password || '',
        options: {
          data: {
            name: data.name.trim(),
            role: 'VOLUNTEER',
            batch: batch || null,
            unit_id: unitRow.id,
            unit_number: data.unitCode,
            date_of_birth: data.dob,
          },
        },
      });

      if (authError) {
        console.error('Supabase Auth signup failed:', authError);
        return { success: false, message: `Registration failed: ${authError.message}` };
      }

      if (!authData.user) {
        return { success: false, message: 'Registration failed: Supabase did not return a user account.' };
      }

      // Create the application profile. user_id is the UUID from auth.users.
      const profile = {
        user_id: authData.user.id,
        name: data.name.trim(),
        email: data.email.trim(),
        role: 'VOLUNTEER',
        batch: batch || null,
        unit_id: unitRow.id,
        date_of_birth: data.dob,
        account_status: 'PENDING',
      };

      const { error: profileError } = await supabase
        .from('users')
        .insert(profile);

      if (profileError) {
        console.error('Supabase users insert failed:', profileError);
        return {
          success: false,
          message: `Auth account was created, but the THANAL profile could not be saved: ${profileError.message}`,
        };
      }

      // Keep the UI responsive without making LocalStorage the source of truth.
      const newVol: VolunteerUser = {
        ...data,
        role: 'VOLUNTEER',
        status: 'PENDING',
        createdAt: systemDate,
      };
      setVolunteers((prev) => [...prev.filter(v => v.email.toLowerCase() !== data.email.toLowerCase()), newVol]);

      return {
        success: true,
        message: `Registration submitted! It is PENDING approval by Volunteer Secretary of ${data.unitCode}.`,
      };
    } catch (error) {
      console.error('Unexpected volunteer registration error:', error);
      return { success: false, message: 'Registration failed unexpectedly. Please try again.' };
    }
  };

  // VS Operations
  const updateVolunteerStatusInDb = async (volunteerId: string, status: 'APPROVED') => {
    const { error } = await supabase.from('users').update({ account_status: status }).eq('user_id', volunteerId);
    if (error) {
      console.error('Supabase status update failed:', error);
      window.alert(`Could not save the change to the database: ${error.message}`);
      loadUnitData();
    }
  };

  const approveVolunteer = (volunteerId: string, vsId: string) => {
    updateVolunteerStatusInDb(volunteerId, 'APPROVED');
    setVolunteers((prev) =>
      prev.map((v) =>
        v.id === volunteerId
          ? {
              ...v,
              status: 'APPROVED',
              approvedAt: systemDate,
              approvedBy: vsId,
            }
          : v
      )
    );
  };

  // Rejecting a volunteer deletes them completely: auth account, profile, plantings,
  // and every local trace (needs the reject_volunteer SQL function in Supabase).
  const rejectVolunteer = async (volunteerId: string) => {
    const { error } = await supabase.rpc('reject_volunteer', { p_volunteer_id: volunteerId });
    if (error) {
      console.error('Supabase volunteer reject failed:', error);
      window.alert(`Could not remove the volunteer: ${error.message}`);
      loadUnitData();
      return;
    }
    setVolunteers((prev) => prev.filter((v) => v.id !== volunteerId));
    setSubmissions((prev) => prev.filter((x) => x.volunteerId !== volunteerId));
    setNotifications((prev) => prev.filter((n) => n.volunteerId !== volunteerId));
  };

  // Planting Submission
  const submitPlanting = async (data: {
    volunteerId: string;
    treeSpecies: string;
    plantingDate: string;
    locationName: string;
    coordinates?: { lat: number; lng: number };
    description: string;
    photoUrl: string;
    photoFileName: string;
    tagApprovalStatus: TagApprovalStatus;
    tagNotes?: string;
  }) => {
    const vol = volunteers.find((v) => v.id === data.volunteerId);
    if (!vol) {
      return { success: false, message: 'Volunteer profile not found.' };
    }
    const currentYear = parseDate(systemDate).getFullYear();

    try {
      const { data: me } = await supabase.from('users').select('unit_id').eq('user_id', vol.id).maybeSingle();
      if (!me?.unit_id) {
        return { success: false, message: 'Please log in again, then retry.' };
      }

      const { data: ds } = await supabase.from('unit_drive_settings').select('script_url').maybeSingle();
      if (!ds?.script_url) {
        return {
          success: false,
          message: "Your unit's Google Drive is not connected yet. Please ask your VS to complete Drive Setup.",
        };
      }

      // 1. Send the photo to the unit's Google Drive folder (Apps Script owned by the VS)
      const safeName = vol.name.replace(/[^A-Za-z0-9 _-]/g, '').trim() || 'volunteer';
      const fileName = `${safeName}_${currentYear}_${Date.now().toString().slice(-5)}.jpg`;
      let upload: any;
      try {
        const resp = await fetch(ds.script_url, {
          method: 'POST',
          body: JSON.stringify({
            volunteer: `${safeName} (${displayId(vol)})`,
            year: currentYear,
            fileName,
            mimeType: 'image/jpeg',
            data: data.photoUrl.split(',')[1] || '',
          }),
        });
        upload = await resp.json();
      } catch (err) {
        console.error('Drive upload request failed:', err);
        return { success: false, message: "Could not reach your unit's Drive. Check your internet and try again." };
      }
      if (!upload?.ok) {
        return { success: false, message: `Drive upload failed: ${upload?.error || 'unknown error'}` };
      }

      // 2. Save the submission record (with the Drive link) in Supabase
      const nowIso = new Date().toISOString();
      const { data: saved, error: saveError } = await supabase
        .from('plantings')
        .upsert(
          {
            volunteer_id: vol.id,
            unit_id: me.unit_id,
            year: currentYear,
            tree_species: data.treeSpecies,
            planting_date: data.plantingDate || null,
            location_name: data.locationName,
            description: data.description,
            photo_url: `https://drive.google.com/thumbnail?id=${upload.id}&sz=w1000`,
            drive_link: upload.url,
            photo_file_name: fileName,
            tag_status: data.tagApprovalStatus,
            tag_notes: data.tagNotes || null,
            updated_at: nowIso,
          },
          { onConflict: 'volunteer_id,year' }
        )
        .select()
        .single();

      if (saveError || !saved) {
        console.error('Supabase plantings save failed:', saveError);
        return {
          success: false,
          message: `Photo reached Drive, but the record could not be saved: ${saveError?.message || 'unknown error'}`,
        };
      }

      const newSub: PlantingSubmission = {
        id: saved.id,
        volunteerId: vol.id,
        volunteerName: vol.name,
        unitId: vol.unitId,
        unitCode: vol.unitCode,
        year: currentYear,
        treeSpecies: data.treeSpecies,
        plantingDate: data.plantingDate,
        locationName: data.locationName,
        coordinates: data.coordinates,
        description: data.description,
        photoUrl: saved.photo_url,
        photoFileName: fileName,
        tagApprovalStatus: data.tagApprovalStatus,
        tagNotes: data.tagNotes,
        submittedAt: saved.submitted_at || nowIso,
        updatedAt: nowIso,
        driveFolderExpected: `THANAL/${vol.unitCode}/${vol.name}/${currentYear}`,
        driveLink: upload.url,
      };
      setSubmissions((prev) => [
        newSub,
        ...prev.filter((x) => !(x.volunteerId === vol.id && x.year === currentYear)),
      ]);

      return {
        success: true,
        message: 'Photo saved to your unit’s Google Drive and planting submitted!',
        submissionId: saved.id,
      };
    } catch (error) {
      console.error('Unexpected planting submit error:', error);
      return { success: false, message: 'Submission failed unexpectedly. Please try again.' };
    }
  };

  const updateTagStatus = (
    submissionId: string,
    newStatus: TagApprovalStatus,
    tagNotes?: string
  ) => {
    setSubmissions((prev) =>
      prev.map((s) =>
        s.id === submissionId
          ? {
              ...s,
              tagApprovalStatus: newStatus,
              tagNotes: tagNotes !== undefined ? tagNotes : s.tagNotes,
              updatedAt: new Date().toISOString(),
            }
          : s
      )
    );
    if (/^[0-9a-f-]{36}$/i.test(submissionId)) {
      clearTimeout(tagTimers.current[submissionId]);
      tagTimers.current[submissionId] = setTimeout(async () => {
        const patch: Record<string, unknown> = { tag_status: newStatus, updated_at: new Date().toISOString() };
        if (tagNotes !== undefined) patch.tag_notes = tagNotes;
        const { error } = await supabase.from('plantings').update(patch).eq('id', submissionId);
        if (error) console.error('Supabase tag update failed:', error);
      }, 600);
    }
  };

  const saveDriveSettings = async (scriptUrl: string, folderUrl: string) => {
    if (!currentUser || currentUser.role !== 'VS') {
      return { success: false, message: 'Only a VS can change Drive settings.' };
    }
    const url = scriptUrl.trim();
    if (!/^https:\/\/script\.google\.com\/.+\/exec$/.test(url)) {
      return { success: false, message: 'The Web app URL should start with https://script.google.com and end with /exec.' };
    }
    const { data: me } = await supabase.from('users').select('unit_id').eq('user_id', currentUser.id).maybeSingle();
    if (!me?.unit_id) return { success: false, message: 'Please log in again, then retry.' };
    const { error } = await supabase.from('unit_drive_settings').upsert(
      { unit_id: me.unit_id, script_url: url, folder_url: folderUrl.trim() || null, updated_at: new Date().toISOString() },
      { onConflict: 'unit_id' }
    );
    if (error) return { success: false, message: error.message };
    setDriveSettings({ scriptUrl: url, folderUrl: folderUrl.trim() });
    return { success: true, message: 'Drive connection saved. Volunteers in your unit can now upload photos.' };
  };

  const testDriveConnection = async (scriptUrl: string) => {
    try {
      const resp = await fetch(scriptUrl.trim());
      const json = await resp.json();
      return json.ok
        ? { success: true, message: `Connected to Drive folder "${json.folder}".` }
        : { success: false, message: json.error || 'Script reached, but the folder was not found. Check FOLDER_ID.' };
    } catch {
      return { success: false, message: 'Could not reach the script. Check the URL ends with /exec and access is set to "Anyone".' };
    }
  };

  const resetDatabase = () => {
    localStorage.clear();
    setUnits(INITIAL_UNITS);
    setVsUsers(INITIAL_VS_USERS);
    setVolunteers(INITIAL_VOLUNTEERS);
    setSubmissions(INITIAL_SUBMISSIONS);
    setNotifications([]);
    setSystemDateState(defaultDateStr);
    setCurrentUser(null);
    setIsProductionModeState(true);
  };

  const setIsProductionMode = (val: boolean) => {
    setIsProductionModeState(val);
    localStorage.setItem(STORAGE_KEYS.IS_PRODUCTION_MODE, String(val));
  };

  const contextValue = useMemo(
    () => ({
      currentUser,
      setCurrentUser,
      units,
      vsUsers,
      volunteers,
      submissions,
      notifications,
      systemDate,
      setSystemDate,
      advanceSystemDateByDays,
      resetSystemDate,
      login,
      logout,
      registerVs,
      registerVolunteer,
      approveVolunteer,
      rejectVolunteer,
      submitPlanting,
      updateTagStatus,
      driveSettings,
      saveDriveSettings,
      testDriveConnection,
      refreshNotifications,
      resetDatabase,
      isProductionMode,
      setIsProductionMode,
    }),
    [
      currentUser,
      units,
      vsUsers,
      volunteers,
      submissions,
      notifications,
      systemDate,
      isProductionMode,
      driveSettings,
    ]
  );

  return (
    <ThanalContext.Provider value={contextValue}>
      {children}
    </ThanalContext.Provider>
  );
};

export const useThanal = () => {
  const context = useContext(ThanalContext);
  if (!context) {
    throw new Error('useThanal must be used within a ThanalProvider');
  }
  return context;
};
