export type Role = 'VS' | 'VOLUNTEER';

export type UserStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';

export type VolunteerActivityStatus =
  | 'UPCOMING'
  | 'ACTIVE'
  | 'PLANTING_SUBMITTED'
  | 'TAG_APPROVAL_PENDING'
  | 'COMPLETED'
  | 'WINDOW_CLOSED';

export type TagApprovalStatus = 'Pending' | 'Yes – Approved' | 'No – Not Approved';

export interface Unit {
  id: string;
  code: string; // e.g. 'GCEK01'
  name: string; // e.g. 'Govt. College of Engineering Kannur - NSS Unit 01'
  college: string; // e.g. 'GCEK Kannur'
  district: string;
  state: string;
  assignedVsIds: string[];
  createdAt: string;
}

export interface BaseUser {
  id: string;
  name: string;
  email: string;
  phone: string;
  password?: string;
  role: Role;
  status: UserStatus;
  createdAt: string;
}

export interface VSUser extends BaseUser {
  role: 'VS';
  college: string;
  unitId: string;
  unitCode: string;
  dob?: string; // YYYY-MM-DD
  shortCode?: string; // e.g. '141-VS' (generated by the database)
  approvedAt?: string;
  approvedBy?: string;
}

export interface VolunteerUser extends BaseUser {
  role: 'VOLUNTEER';
  dob: string; // YYYY-MM-DD
  batch?: string; // 2-digit joining year, e.g. '24' or '25'
  shortCode?: string; // e.g. '141-24-V001' (generated by the database)
  unitId: string;
  unitCode: string;
  college: string;
  approvedAt?: string;
  approvedBy?: string;
}

export type AnyUser = VSUser | VolunteerUser;

export interface PlantingSubmission {
  id: string;
  volunteerId: string;
  volunteerName: string;
  unitId: string;
  unitCode: string;
  year: number;
  treeSpecies: string;
  plantingDate: string; // YYYY-MM-DD
  locationName: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
  description: string;
  photoUrl: string;
  photoFileName: string;
  tagApprovalStatus: TagApprovalStatus;
  tagNotes?: string;
  submittedAt: string;
  updatedAt: string;
  driveFolderExpected: string;
  driveLink?: string;
}

export interface NotificationLog {
  id: string;
  volunteerId: string;
  volunteerName: string;
  recipientEmail: string;
  type: 'WINDOW_START_REMINDER' | 'BIRTHDAY_WISH' | 'STATUS_UPDATE';
  subject: string;
  body: string;
  sentAt: string;
  year: number;
}

export interface ThanalWindowInfo {
  year: number;
  birthdayDate: string; // YYYY-MM-DD
  startDate: string; // YYYY-MM-DD (10 days before)
  endDate: string; // YYYY-MM-DD (10 days after)
  totalDays: number; // 21
  dayNumberInWindow?: number; // 1 to 21
  daysRemaining?: number;
  daysUntilWindowStarts?: number;
  isTodayBirthday: boolean;
  isWindowActive: boolean;
  isWindowUpcoming: boolean;
  isWindowPast: boolean;
}
